require "lol/client"

require "lol/request"
require "lol/champion_request"
require "lol/game_request"

require "lol/model"
require "lol/champion"
require "lol/game"
require "lol/league"
require "lol/player"
require "lol/raw_statistic"
require "lol/player_statistic"
require "lol/aggregated_statistic"
require "lol/ranked_statistics_summary"
require "lol/champion_statistics_summary"
require "lol/champion_statistic"
require "lol/team"
require "lol/roster"
require "lol/team_member"
require "lol/team_statistic"
require "lol/match_summary"
require "lol/league_entry"
require "lol/mini_series"
